export const ADD_NUMBER = 'ADD_NUMBER';
export const ADD_USER = 'ADD_USER';
export const LOGOFF_USER = 'LOGOFF_USER';
export const CHANGE_LAST_CONNEXION = 'CHANGE_LAST_CONNEXION';
export const CHANGE_LAST_REFRESH = 'CHANGE_LAST_REFRESH';
export const SOCKET_MESSAGE = 'SOCKET_MESSAGE';
